DirectoryIndex index.php

RedirectMatch 302 ^/frontend/index\.html$ /

<FilesMatch "\.(html|php)$">
    Header always set Cache-Control "no-store, no-cache, must-revalidate"
    Header always set Pragma "no-cache"
</FilesMatch>
