BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS public.componentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'indisponivel',
    status_cadastro TEXT,
    estoque_atualizado_em TIMESTAMPTZ,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT componentes_codigo_unique UNIQUE (codigo),
    CONSTRAINT componentes_codigo_not_blank CHECK (BTRIM(codigo) <> ''),
    CONSTRAINT componentes_descricao_not_blank CHECK (BTRIM(descricao) <> ''),
    CONSTRAINT componentes_status_check CHECK (status IN ('disponivel', 'indisponivel')),
    CONSTRAINT componentes_status_cadastro_check CHECK (status_cadastro IS NULL OR status_cadastro IN ('obsoleto', 'descontinuado'))
);

ALTER TABLE public.componentes
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'indisponivel';

ALTER TABLE public.componentes
    ADD COLUMN IF NOT EXISTS status_cadastro TEXT;

ALTER TABLE public.componentes
    ADD COLUMN IF NOT EXISTS estoque_atualizado_em TIMESTAMPTZ;

UPDATE public.componentes
SET status = 'indisponivel'
WHERE status IS NULL OR status = '';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'componentes_status_check'
    ) THEN
        ALTER TABLE public.componentes
            ADD CONSTRAINT componentes_status_check CHECK (status IN ('disponivel', 'indisponivel'));
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'componentes_status_cadastro_check'
    ) THEN
        ALTER TABLE public.componentes
            ADD CONSTRAINT componentes_status_cadastro_check CHECK (status_cadastro IS NULL OR status_cadastro IN ('obsoleto', 'descontinuado'));
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL,
    senha_hash TEXT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT usuarios_login_unique UNIQUE (login),
    CONSTRAINT usuarios_login_lowercase CHECK (login = LOWER(login)),
    CONSTRAINT usuarios_login_not_blank CHECK (BTRIM(login) <> ''),
    CONSTRAINT usuarios_senha_hash_not_blank CHECK (BTRIM(senha_hash) <> '')
);

CREATE INDEX IF NOT EXISTS idx_componentes_codigo_trgm
    ON public.componentes USING GIN (codigo gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_componentes_descricao_trgm
    ON public.componentes USING GIN (descricao gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_componentes_status
    ON public.componentes (status);

CREATE INDEX IF NOT EXISTS idx_componentes_status_cadastro
    ON public.componentes (status_cadastro);

CREATE OR REPLACE FUNCTION public.set_componentes_atualizado_em()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_componentes_atualizado_em
    ON public.componentes;

CREATE TRIGGER trg_componentes_atualizado_em
BEFORE UPDATE ON public.componentes
FOR EACH ROW
EXECUTE FUNCTION public.set_componentes_atualizado_em();

-- Permite consulta pela Neon Data API quando o papel anonymous estiver ativo.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anonymous') THEN
        GRANT USAGE ON SCHEMA public TO anonymous;
        GRANT SELECT ON TABLE public.componentes TO anonymous;
        REVOKE ALL ON TABLE public.usuarios FROM anonymous;
    END IF;
END;
$$;

COMMIT;
