BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS public.componentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT componentes_codigo_unique UNIQUE (codigo),
    CONSTRAINT componentes_codigo_not_blank CHECK (BTRIM(codigo) <> ''),
    CONSTRAINT componentes_descricao_not_blank CHECK (BTRIM(descricao) <> '')
);

CREATE INDEX IF NOT EXISTS idx_componentes_codigo_trgm
    ON public.componentes USING GIN (codigo gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_componentes_descricao_trgm
    ON public.componentes USING GIN (descricao gin_trgm_ops);

CREATE OR REPLACE FUNCTION public.set_componentes_atualizado_em()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_componentes_atualizado_em
    ON public.componentes;

CREATE TRIGGER trg_componentes_atualizado_em
BEFORE UPDATE ON public.componentes
FOR EACH ROW
EXECUTE FUNCTION public.set_componentes_atualizado_em();

-- Permite consulta pela Neon Data API quando o papel anonymous estiver ativo.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anonymous') THEN
        GRANT USAGE ON SCHEMA public TO anonymous;
        GRANT SELECT ON TABLE public.componentes TO anonymous;
    END IF;
END;
$$;

COMMIT;
